language: python

sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - python-lxml

python:
  - "2.7"

env:
  global:
  - LINT_CHECK="0" TESTS="0"

  matrix:
  - LINT_CHECK="1"
  - TESTS="1"

install:
  - python -c "import lxml;print lxml.__file__"


